import { ComponentStructure } from "./types";

export const inputsStructure: ComponentStructure = {
  componentType: "inputs",
  variants: [
    {
      id: "inputs1",
      name: "Advanced Inputs System 1 - Dynamic Forms",
      fields: [
        { key: "visible", label: "Visible", type: "boolean" },
        {
          key: "layout",
          label: "Layout Settings",
          type: "object",
          fields: [
            {
              key: "direction",
              label: "Direction",
              type: "select",
              options: [
                { value: "rtl", label: "Right to Left" },
                { value: "ltr", label: "Left to Right" },
              ],
            },
            {
              key: "maxWidth",
              label: "Max Width",
              type: "text",
              placeholder: "max-w-7xl",
            },
            {
              key: "containerPadding",
              label: "Container Padding",
              type: "text",
              placeholder: "p-4",
            },
            {
              key: "cardsSpacing",
              label: "Cards Spacing",
              type: "text",
              placeholder: "space-y-8",
            },
          ],
        },
        {
          key: "theme",
          label: "Global Theme",
          type: "object",
          fields: [
            {
              key: "primaryColor",
              label: "Primary Color",
              type: "color",
              placeholder: "#3b82f6",
            },
            {
              key: "secondaryColor",
              label: "Secondary Color",
              type: "color",
              placeholder: "#2563eb",
            },
            {
              key: "accentColor",
              label: "Accent Color",
              type: "color",
              placeholder: "#1d4ed8",
            },
            {
              key: "submitButtonGradient",
              label: "Submit Button Gradient",
              type: "text",
              placeholder: "linear-gradient(135deg, #3b82f6 0%, #6366f1 100%)",
            },
          ],
        },
        {
          key: "submitButton",
          label: "Submit Button",
          type: "object",
          fields: [
            { key: "show", label: "Show Submit Button", type: "boolean" },
            {
              key: "text",
              label: "Button Text",
              type: "text",
              placeholder: "حفظ جميع البيانات",
            },
            {
              key: "style",
              label: "Button Style",
              type: "object",
              fields: [
                {
                  key: "className",
                  label: "CSS Classes",
                  type: "text",
                  placeholder:
                    "px-8 py-4 text-white rounded-xl transition-all duration-300 flex items-center space-x-2 rtl:space-x-reverse font-bold text-lg shadow-lg hover:shadow-xl disabled:opacity-50 disabled:cursor-not-allowed",
                },
                {
                  key: "padding",
                  label: "Padding",
                  type: "text",
                  placeholder: "px-8 py-4",
                },
                {
                  key: "borderRadius",
                  label: "Border Radius",
                  type: "text",
                  placeholder: "rounded-xl",
                },
                {
                  key: "fontWeight",
                  label: "Font Weight",
                  type: "text",
                  placeholder: "font-bold",
                },
                {
                  key: "fontSize",
                  label: "Font Size",
                  type: "text",
                  placeholder: "text-lg",
                },
                {
                  key: "shadow",
                  label: "Shadow",
                  type: "text",
                  placeholder: "shadow-lg hover:shadow-xl",
                },
              ],
            },
            {
              key: "animation",
              label: "Button Animation",
              type: "object",
              fields: [
                { key: "enabled", label: "Enable Animation", type: "boolean" },
                {
                  key: "type",
                  label: "Animation Type",
                  type: "select",
                  options: [
                    { value: "gradient-shift", label: "Gradient Shift" },
                    { value: "pulse", label: "Pulse" },
                    { value: "bounce", label: "Bounce" },
                    { value: "none", label: "None" },
                  ],
                },
                {
                  key: "duration",
                  label: "Duration (s)",
                  type: "number",
                  placeholder: "3",
                },
                {
                  key: "delay",
                  label: "Delay (s)",
                  type: "number",
                  placeholder: "0",
                },
              ],
            },
          ],
        },
        {
          key: "cards",
          label: "Input Cards",
          type: "array",
          addLabel: "Add Input Card",
          itemLabel: "Input Card",
          of: [
            { key: "title", label: "Card Title", type: "text" },
            { key: "description", label: "Card Description", type: "text" },
            {
              key: "icon",
              label: "Card Icon",
              type: "object",
              fields: [
                {
                  key: "type",
                  label: "Icon Type",
                  type: "select",
                  options: [
                    { value: "DollarSign", label: "Dollar Sign" },
                    { value: "Building", label: "Building" },
                    { value: "User", label: "User" },
                    { value: "CreditCard", label: "Credit Card" },
                    { value: "FileText", label: "File Text" },
                    { value: "Calendar", label: "Calendar" },
                    { value: "Tag", label: "Tag" },
                    { value: "Phone", label: "Phone" },
                    { value: "Mail", label: "Mail" },
                    { value: "Settings", label: "Settings" },
                    { value: "Shield", label: "Shield" },
                    { value: "Star", label: "Star" },
                  ],
                },
                {
                  key: "size",
                  label: "Icon Size",
                  type: "number",
                  placeholder: "24",
                },
              ],
            },
            {
              key: "color",
              label: "Card Color",
              type: "select",
              options: [
                { value: "blue", label: "Blue" },
                { value: "indigo", label: "Indigo" },
                { value: "purple", label: "Purple" },
                { value: "pink", label: "Pink" },
                { value: "red", label: "Red" },
                { value: "green", label: "Green" },
                { value: "yellow", label: "Yellow" },
                { value: "orange", label: "Orange" },
                { value: "teal", label: "Teal" },
                { value: "cyan", label: "Cyan" },
                { value: "emerald", label: "Emerald" },
                { value: "violet", label: "Violet" },
                { value: "fuchsia", label: "Fuchsia" },
                { value: "rose", label: "Rose" },
                { value: "sky", label: "Sky" },
                { value: "lime", label: "Lime" },
                { value: "amber", label: "Amber" },
                { value: "slate", label: "Slate" },
                { value: "gray", label: "Gray" },
                { value: "zinc", label: "Zinc" },
                { value: "neutral", label: "Neutral" },
                { value: "stone", label: "Stone" },
              ],
            },
            {
              key: "customColors",
              label: "Custom Colors",
              type: "object",
              fields: [
                {
                  key: "primary",
                  label: "Primary Color",
                  type: "color",
                  placeholder: "#3b82f6",
                },
                {
                  key: "secondary",
                  label: "Secondary Color",
                  type: "color",
                  placeholder: "#2563eb",
                },
                {
                  key: "hover",
                  label: "Hover Color",
                  type: "color",
                  placeholder: "#1d4ed8",
                },
                {
                  key: "shadow",
                  label: "Shadow Color",
                  type: "color",
                  placeholder: "rgba(59, 130, 246, 0.15)",
                },
              ],
            },
            { key: "isCollapsible", label: "Is Collapsible", type: "boolean" },
            { key: "showAddButton", label: "Show Add Button", type: "boolean" },
            {
              key: "addButtonText",
              label: "Add Button Text",
              type: "text",
              placeholder: "إضافة جديد",
            },
            {
              key: "fields",
              label: "Input Fields",
              type: "array",
              addLabel: "Add Field",
              itemLabel: "Field",
              of: [
                { key: "label", label: "Field Label", type: "text" },
                { key: "placeholder", label: "Placeholder", type: "text" },
                { key: "description", label: "Description", type: "text" },
                { key: "required", label: "Required", type: "boolean" },
                {
                  key: "type",
                  label: "Field Type",
                  type: "select",
                  options: [
                    { value: "text", label: "Text" },
                    { value: "email", label: "Email" },
                    { value: "password", label: "Password" },
                    { value: "number", label: "Number" },
                    { value: "date", label: "Date" },
                    { value: "select", label: "Select" },
                    { value: "textarea", label: "Textarea" },
                    { value: "currency", label: "Currency" },
                  ],
                },
                {
                  key: "options",
                  label: "Select Options",
                  type: "array",
                  addLabel: "Add Option",
                  itemLabel: "Option",
                  of: [
                    { key: "value", label: "Value", type: "text" },
                    { key: "label", label: "Label", type: "text" },
                  ],
                },
                {
                  key: "validation",
                  label: "Validation Rules",
                  type: "object",
                  fields: [
                    { key: "min", label: "Minimum Value", type: "number" },
                    { key: "max", label: "Maximum Value", type: "number" },
                    { key: "pattern", label: "Pattern (Regex)", type: "text" },
                    { key: "message", label: "Error Message", type: "text" },
                  ],
                },
                {
                  key: "icon",
                  label: "Field Icon",
                  type: "object",
                  fields: [
                    {
                      key: "type",
                      label: "Icon Type",
                      type: "select",
                      options: [
                        { value: "DollarSign", label: "Dollar Sign" },
                        { value: "Calendar", label: "Calendar" },
                        { value: "Tag", label: "Tag" },
                        { value: "FileText", label: "File Text" },
                        { value: "User", label: "User" },
                        { value: "Phone", label: "Phone" },
                        { value: "Mail", label: "Mail" },
                        { value: "Building", label: "Building" },
                        { value: "CreditCard", label: "Credit Card" },
                        { value: "Settings", label: "Settings" },
                        { value: "Shield", label: "Shield" },
                        { value: "Star", label: "Star" },
                      ],
                    },
                    {
                      key: "size",
                      label: "Icon Size",
                      type: "number",
                      placeholder: "20",
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          key: "cardStyle",
          label: "Card Style",
          type: "object",
          fields: [
            {
              key: "container",
              label: "Card Container",
              type: "object",
              fields: [
                {
                  key: "className",
                  label: "CSS Classes",
                  type: "text",
                  placeholder:
                    "bg-white dark:bg-gray-800 rounded-2xl shadow-lg border border-gray-200 dark:border-gray-700 overflow-hidden transition-all duration-300",
                },
                {
                  key: "backgroundColor",
                  label: "Background Color",
                  type: "text",
                  placeholder: "bg-white dark:bg-gray-800",
                },
                {
                  key: "borderRadius",
                  label: "Border Radius",
                  type: "text",
                  placeholder: "rounded-2xl",
                },
                {
                  key: "shadow",
                  label: "Shadow",
                  type: "text",
                  placeholder: "shadow-lg",
                },
                {
                  key: "border",
                  label: "Border",
                  type: "text",
                  placeholder: "border border-gray-200 dark:border-gray-700",
                },
                {
                  key: "transition",
                  label: "Transition",
                  type: "text",
                  placeholder: "transition-all duration-300",
                },
              ],
            },
            {
              key: "header",
              label: "Card Header",
              type: "object",
              fields: [
                {
                  key: "className",
                  label: "CSS Classes",
                  type: "text",
                  placeholder: "p-6 text-white transition-all duration-300",
                },
                {
                  key: "padding",
                  label: "Padding",
                  type: "text",
                  placeholder: "p-6",
                },
                {
                  key: "textColor",
                  label: "Text Color",
                  type: "text",
                  placeholder: "text-white",
                },
                {
                  key: "transition",
                  label: "Transition",
                  type: "text",
                  placeholder: "transition-all duration-300",
                },
              ],
            },
            {
              key: "content",
              label: "Card Content",
              type: "object",
              fields: [
                {
                  key: "className",
                  label: "CSS Classes",
                  type: "text",
                  placeholder: "p-6",
                },
                {
                  key: "padding",
                  label: "Padding",
                  type: "text",
                  placeholder: "p-6",
                },
                {
                  key: "grid",
                  label: "Grid Layout",
                  type: "object",
                  fields: [
                    {
                      key: "className",
                      label: "CSS Classes",
                      type: "text",
                      placeholder:
                        "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6",
                    },
                    {
                      key: "gap",
                      label: "Gap",
                      type: "text",
                      placeholder: "gap-6",
                    },
                    {
                      key: "columns",
                      label: "Columns",
                      type: "object",
                      fields: [
                        {
                          key: "mobile",
                          label: "Mobile",
                          type: "text",
                          placeholder: "grid-cols-1",
                        },
                        {
                          key: "tablet",
                          label: "Tablet",
                          type: "text",
                          placeholder: "md:grid-cols-2",
                        },
                        {
                          key: "desktop",
                          label: "Desktop",
                          type: "text",
                          placeholder: "lg:grid-cols-3",
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          key: "inputStyle",
          label: "Input Field Style",
          type: "object",
          fields: [
            {
              key: "container",
              label: "Input Container",
              type: "object",
              fields: [
                {
                  key: "className",
                  label: "CSS Classes",
                  type: "text",
                  placeholder: "relative",
                },
              ],
            },
            {
              key: "label",
              label: "Input Label",
              type: "object",
              fields: [
                {
                  key: "className",
                  label: "CSS Classes",
                  type: "text",
                  placeholder:
                    "block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2",
                },
                {
                  key: "fontSize",
                  label: "Font Size",
                  type: "text",
                  placeholder: "text-sm",
                },
                {
                  key: "fontWeight",
                  label: "Font Weight",
                  type: "text",
                  placeholder: "font-medium",
                },
                {
                  key: "color",
                  label: "Color",
                  type: "text",
                  placeholder: "text-gray-700 dark:text-gray-300",
                },
                {
                  key: "marginBottom",
                  label: "Margin Bottom",
                  type: "text",
                  placeholder: "mb-2",
                },
              ],
            },
            {
              key: "input",
              label: "Input Field",
              type: "object",
              fields: [
                {
                  key: "className",
                  label: "CSS Classes",
                  type: "text",
                  placeholder:
                    "w-full px-4 py-3 pr-10 border rounded-xl transition-all duration-300 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent dark:bg-gray-800 dark:border-gray-600 dark:text-white border-gray-300 hover:border-gray-400 dark:hover:border-gray-500",
                },
                {
                  key: "padding",
                  label: "Padding",
                  type: "text",
                  placeholder: "px-4 py-3 pr-10",
                },
                {
                  key: "borderRadius",
                  label: "Border Radius",
                  type: "text",
                  placeholder: "rounded-xl",
                },
                {
                  key: "transition",
                  label: "Transition",
                  type: "text",
                  placeholder: "transition-all duration-300",
                },
                {
                  key: "focus",
                  label: "Focus State",
                  type: "text",
                  placeholder:
                    "focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent",
                },
                {
                  key: "darkMode",
                  label: "Dark Mode",
                  type: "text",
                  placeholder:
                    "dark:bg-gray-800 dark:border-gray-600 dark:text-white",
                },
                {
                  key: "hover",
                  label: "Hover State",
                  type: "text",
                  placeholder:
                    "hover:border-gray-400 dark:hover:border-gray-500",
                },
              ],
            },
            {
              key: "error",
              label: "Error State",
              type: "object",
              fields: [
                {
                  key: "className",
                  label: "CSS Classes",
                  type: "text",
                  placeholder: "border-red-500 bg-red-50 dark:bg-red-900/20",
                },
                {
                  key: "borderColor",
                  label: "Border Color",
                  type: "text",
                  placeholder: "border-red-500",
                },
                {
                  key: "backgroundColor",
                  label: "Background Color",
                  type: "text",
                  placeholder: "bg-red-50 dark:bg-red-900/20",
                },
              ],
            },
            {
              key: "errorMessage",
              label: "Error Message",
              type: "object",
              fields: [
                {
                  key: "className",
                  label: "CSS Classes",
                  type: "text",
                  placeholder: "flex items-center mt-2 text-red-500 text-sm",
                },
                {
                  key: "color",
                  label: "Color",
                  type: "text",
                  placeholder: "text-red-500",
                },
                {
                  key: "fontSize",
                  label: "Font Size",
                  type: "text",
                  placeholder: "text-sm",
                },
                {
                  key: "marginTop",
                  label: "Margin Top",
                  type: "text",
                  placeholder: "mt-2",
                },
              ],
            },
          ],
        },
        {
          key: "animations",
          label: "Animations",
          type: "object",
          fields: [
            {
              key: "card",
              label: "Card Animation",
              type: "object",
              fields: [
                { key: "enabled", label: "Enable Animation", type: "boolean" },
                {
                  key: "type",
                  label: "Animation Type",
                  type: "select",
                  options: [
                    { value: "fade-up", label: "Fade Up" },
                    { value: "fade-down", label: "Fade Down" },
                    { value: "fade-left", label: "Fade Left" },
                    { value: "fade-right", label: "Fade Right" },
                    { value: "slide-up", label: "Slide Up" },
                    { value: "slide-down", label: "Slide Down" },
                    { value: "scale", label: "Scale" },
                    { value: "none", label: "None" },
                  ],
                },
                {
                  key: "duration",
                  label: "Duration (ms)",
                  type: "number",
                  placeholder: "400",
                },
                {
                  key: "delay",
                  label: "Delay (ms)",
                  type: "number",
                  placeholder: "0",
                },
                {
                  key: "stagger",
                  label: "Stagger Delay (ms)",
                  type: "number",
                  placeholder: "100",
                },
              ],
            },
            {
              key: "fields",
              label: "Fields Animation",
              type: "object",
              fields: [
                { key: "enabled", label: "Enable Animation", type: "boolean" },
                {
                  key: "type",
                  label: "Animation Type",
                  type: "select",
                  options: [
                    { value: "fade-up", label: "Fade Up" },
                    { value: "fade-down", label: "Fade Down" },
                    { value: "fade-left", label: "Fade Left" },
                    { value: "fade-right", label: "Fade Right" },
                    { value: "slide-up", label: "Slide Up" },
                    { value: "slide-down", label: "Slide Down" },
                    { value: "scale", label: "Scale" },
                    { value: "none", label: "None" },
                  ],
                },
                {
                  key: "duration",
                  label: "Duration (ms)",
                  type: "number",
                  placeholder: "300",
                },
                {
                  key: "delay",
                  label: "Delay (ms)",
                  type: "number",
                  placeholder: "0",
                },
                {
                  key: "stagger",
                  label: "Stagger Delay (ms)",
                  type: "number",
                  placeholder: "50",
                },
              ],
            },
            {
              key: "submitButton",
              label: "Submit Button Animation",
              type: "object",
              fields: [
                { key: "enabled", label: "Enable Animation", type: "boolean" },
                {
                  key: "type",
                  label: "Animation Type",
                  type: "select",
                  options: [
                    { value: "fade-up", label: "Fade Up" },
                    { value: "fade-down", label: "Fade Down" },
                    { value: "fade-left", label: "Fade Left" },
                    { value: "fade-right", label: "Fade Right" },
                    { value: "slide-up", label: "Slide Up" },
                    { value: "slide-down", label: "Slide Down" },
                    { value: "scale", label: "Scale" },
                    { value: "none", label: "None" },
                  ],
                },
                {
                  key: "duration",
                  label: "Duration (ms)",
                  type: "number",
                  placeholder: "500",
                },
                {
                  key: "delay",
                  label: "Delay (ms)",
                  type: "number",
                  placeholder: "500",
                },
              ],
            },
          ],
        },
        {
          key: "responsive",
          label: "Responsive Design",
          type: "object",
          fields: [
            {
              key: "mobile",
              label: "Mobile",
              type: "object",
              fields: [
                {
                  key: "containerPadding",
                  label: "Container Padding",
                  type: "text",
                  placeholder: "p-4",
                },
                {
                  key: "cardsSpacing",
                  label: "Cards Spacing",
                  type: "text",
                  placeholder: "space-y-6",
                },
                {
                  key: "gridColumns",
                  label: "Grid Columns",
                  type: "text",
                  placeholder: "grid-cols-1",
                },
                {
                  key: "cardPadding",
                  label: "Card Padding",
                  type: "text",
                  placeholder: "p-4",
                },
              ],
            },
            {
              key: "tablet",
              label: "Tablet",
              type: "object",
              fields: [
                {
                  key: "containerPadding",
                  label: "Container Padding",
                  type: "text",
                  placeholder: "md:p-6",
                },
                {
                  key: "cardsSpacing",
                  label: "Cards Spacing",
                  type: "text",
                  placeholder: "md:space-y-8",
                },
                {
                  key: "gridColumns",
                  label: "Grid Columns",
                  type: "text",
                  placeholder: "md:grid-cols-2",
                },
                {
                  key: "cardPadding",
                  label: "Card Padding",
                  type: "text",
                  placeholder: "md:p-6",
                },
              ],
            },
            {
              key: "desktop",
              label: "Desktop",
              type: "object",
              fields: [
                {
                  key: "containerPadding",
                  label: "Container Padding",
                  type: "text",
                  placeholder: "lg:p-8",
                },
                {
                  key: "cardsSpacing",
                  label: "Cards Spacing",
                  type: "text",
                  placeholder: "lg:space-y-10",
                },
                {
                  key: "gridColumns",
                  label: "Grid Columns",
                  type: "text",
                  placeholder: "lg:grid-cols-3",
                },
                {
                  key: "cardPadding",
                  label: "Card Padding",
                  type: "text",
                  placeholder: "lg:p-8",
                },
              ],
            },
          ],
        },
        {
          key: "colors",
          label: "Color System",
          type: "object",
          fields: [
            {
              key: "background",
              label: "Background Color",
              type: "color",
              placeholder: "#f9fafb",
            },
            {
              key: "cardBackground",
              label: "Card Background",
              type: "color",
              placeholder: "#ffffff",
            },
            {
              key: "textPrimary",
              label: "Primary Text Color",
              type: "color",
              placeholder: "#111827",
            },
            {
              key: "textSecondary",
              label: "Secondary Text Color",
              type: "color",
              placeholder: "#6b7280",
            },
            {
              key: "borderColor",
              label: "Border Color",
              type: "color",
              placeholder: "#e5e7eb",
            },
            {
              key: "focusColor",
              label: "Focus Color",
              type: "color",
              placeholder: "#3b82f6",
            },
            {
              key: "errorColor",
              label: "Error Color",
              type: "color",
              placeholder: "#ef4444",
            },
            {
              key: "successColor",
              label: "Success Color",
              type: "color",
              placeholder: "#10b981",
            },
          ],
        },
      ],
      simpleFields: [
        { key: "visible", label: "Visible", type: "boolean" },
        { key: "layout.direction", label: "Direction", type: "select" },
        { key: "layout.maxWidth", label: "Max Width", type: "text" },
        { key: "theme.primaryColor", label: "Primary Color", type: "color" },
        {
          key: "theme.secondaryColor",
          label: "Secondary Color",
          type: "color",
        },
        {
          key: "submitButton.show",
          label: "Show Submit Button",
          type: "boolean",
        },
        { key: "submitButton.text", label: "Submit Button Text", type: "text" },
        { key: "cards", label: "Input Cards", type: "array" },
        {
          key: "animations.card.enabled",
          label: "Card Animation",
          type: "boolean",
        },
        {
          key: "animations.fields.enabled",
          label: "Fields Animation",
          type: "boolean",
        },
        {
          key: "animations.submitButton.enabled",
          label: "Submit Button Animation",
          type: "boolean",
        },
        { key: "colors.background", label: "Background Color", type: "color" },
        {
          key: "colors.cardBackground",
          label: "Card Background",
          type: "color",
        },
        {
          key: "colors.textPrimary",
          label: "Primary Text Color",
          type: "color",
        },
        {
          key: "colors.textSecondary",
          label: "Secondary Text Color",
          type: "color",
        },
        { key: "colors.focusColor", label: "Focus Color", type: "color" },
        { key: "colors.errorColor", label: "Error Color", type: "color" },
        { key: "colors.successColor", label: "Success Color", type: "color" },
      ],
    },
  ],
};
