// context/store/neighborhoods.js
module.exports = {
  neighborhoods: [
    {
      id: 10100003001,
      name_ar: "حي العمل",
      name_en: "Al Amal Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003002,
      name_ar: "حي النموذجية",
      name_en: "Al Namudhajiyah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003003,
      name_ar: "حي الجرادية",
      name_en: "Al Jarradiyah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003004,
      name_ar: "حي الصناعية",
      name_en: "Al Sinaiyah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003005,
      name_ar: "حي منفوحة الجديدة",
      name_en: "Manfuha Al Jadidah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003006,
      name_ar: "حي الفاخرية",
      name_en: "Al Fakhiriyah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003007,
      name_ar: "حي الديرة",
      name_en: "Al Dirah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003008,
      name_ar: "حي ام الحمام الشرقي",
      name_en: "East Umm Al Hamam Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003009,
      name_ar: "حي الشرفية",
      name_en: "Al Sharafiyah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003010,
      name_ar: "حي الهدا",
      name_en: "Al Hada Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003011,
      name_ar: "حي المعذر الشمالي",
      name_en: "North Mathar Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003012,
      name_ar: "حي ام الحمام الغربي",
      name_en: "West Umm Al Hamam Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003013,
      name_ar: "حي الرحمانية",
      name_en: "Al Rahmaniyah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003014,
      name_ar: "حي لبن",
      name_en: "Laban Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003015,
      name_ar: "حي الرفيعة",
      name_en: "Al Rafeah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003016,
      name_ar: "حي الشهداء",
      name_en: "Al Shohda Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003017,
      name_ar: "حي الملك فهد",
      name_en: "King Fahd Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003018,
      name_ar: "حي السويدي",
      name_en: "Al Suwaidi Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003019,
      name_ar: "حي الحزم",
      name_en: "Al Hazm Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003020,
      name_ar: "حي عتيقة",
      name_en: "Utayqah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003021,
      name_ar: "حي المربع",
      name_en: "Al Murabba Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003022,
      name_ar: "حي الفلاح",
      name_en: "Al Falah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003023,
      name_ar: "حي الندى",
      name_en: "Al Nada Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003024,
      name_ar: "حي المرسلات",
      name_en: "Al Mursalat Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003025,
      name_ar: "حي النزهة",
      name_en: "Al Nuzha Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003026,
      name_ar: "حي الورود",
      name_en: "Al Woroud Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003027,
      name_ar: "حي الملك فيصل",
      name_en: "King Faisal Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003028,
      name_ar: "المدينة الصناعية الثانية",
      name_en: "2Nd Industrial City",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003029,
      name_ar: "حي العزيزية",
      name_en: "Al Aziziyah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003030,
      name_ar: "حي المنصورة",
      name_en: "Al Mansurah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003031,
      name_ar: "حي غبيرة",
      name_en: "Ghobairah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003032,
      name_ar: "حي الفاروق",
      name_en: "Al Farooq Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003033,
      name_ar: "حي الفيصلية",
      name_en: "Al Faisaliyah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003034,
      name_ar: "حي الخالدية",
      name_en: "Al Khalidiyah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003035,
      name_ar: "حي الجزيرة",
      name_en: "Al Jazeerah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003036,
      name_ar: "حي السعادة",
      name_en: "Al Saadah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003037,
      name_ar: "حي الناصرية",
      name_en: "Al Nasiriyah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003038,
      name_ar: "حي المناخ",
      name_en: "Al Manakh Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003039,
      name_ar: "حي الدفاع",
      name_en: "Al Difaa Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003040,
      name_ar: "حي النور",
      name_en: "Al Noor Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003041,
      name_ar: "حي الملك عبدالله",
      name_en: "King Abdullah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003042,
      name_ar: "حي الملك سلمان",
      name_en: "King Salman Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003043,
      name_ar: "حي صلاح الدين",
      name_en: "Salahuddin Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003044,
      name_ar: "حي الملك عبدالعزيز",
      name_en: "King Abdulaziz Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003045,
      name_ar: "حي الوزارات",
      name_en: "Al Wizarat Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003046,
      name_ar: "حي سكيرينة",
      name_en: "Skirinah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003047,
      name_ar: "حي الربوة",
      name_en: "Al Rabwah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003048,
      name_ar: "حي جرير",
      name_en: "Jareer Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003049,
      name_ar: "حي المعذر",
      name_en: "Al Mathar Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003050,
      name_ar: "حي الصالحية",
      name_en: "As Salhiyah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003051,
      name_ar: "حي الملز",
      name_en: "Al Malaz Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003052,
      name_ar: "حي منفوحة",
      name_en: "Manfuhah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003053,
      name_ar: "حي عليشة",
      name_en: "Olaishah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003054,
      name_ar: "حي النهضة",
      name_en: "Al Nahdah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003055,
      name_ar: "حي الخليج",
      name_en: "Al Khaleej Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003056,
      name_ar: "حي الضباط",
      name_en: "Al Dhubbat Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003057,
      name_ar: "حي السويدي الغربي",
      name_en: "West Suwaidi Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003058,
      name_ar: "حي ديراب",
      name_en: "Dirab Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003059,
      name_ar: "حي احد",
      name_en: "Ohod Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003060,
      name_ar: "حي نمار",
      name_en: "Namar Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003061,
      name_ar: "حي الشفا",
      name_en: "Al Shifa Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003062,
      name_ar: "حي المحمدية",
      name_en: "Al Muhammadiyah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003063,
      name_ar: "حي السليمانية",
      name_en: "Al Sulaimaniyah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003064,
      name_ar: "حي المروة",
      name_en: "Al Marwah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003065,
      name_ar: "حي عكاظ",
      name_en: "Okaz Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003066,
      name_ar: "حي شبرا",
      name_en: "Shubra Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003067,
      name_ar: "حي الزهرة",
      name_en: "Al Zahrah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003068,
      name_ar: "حي صياح",
      name_en: "Siyah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003069,
      name_ar: "حي سلطانة",
      name_en: "Sultanah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003070,
      name_ar: "حي اليمامة",
      name_en: "Al Yamamah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003071,
      name_ar: "حي البديعة",
      name_en: "Al Badeah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003072,
      name_ar: "حي المصانع",
      name_en: "Al Masani Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003073,
      name_ar: "حي القادسية",
      name_en: "Al Qadisiyah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003074,
      name_ar: "حي الصفا",
      name_en: "Al Safa Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003075,
      name_ar: "حي العليا",
      name_en: "Al Olaya Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003076,
      name_ar: "حي الدريهمية",
      name_en: "Al Duraihemiyah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003077,
      name_ar: "حي الاسكان",
      name_en: "Al Iskan Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003078,
      name_ar: "حي السلام",
      name_en: "Al Salam Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003079,
      name_ar: "حي المنار",
      name_en: "Al Manar Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003080,
      name_ar: "حي النسيم الشرقي",
      name_en: "East Naseem Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003081,
      name_ar: "حي القدس",
      name_en: "Al Quds Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003082,
      name_ar: "حي الوادي",
      name_en: "Al Wadi Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003083,
      name_ar: "حي النفل",
      name_en: "Al Nafel Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003084,
      name_ar: "حي المصيف",
      name_en: "Al Maseef Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003085,
      name_ar: "حي التعاون",
      name_en: "Al Taawun Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003086,
      name_ar: "حي الازدهار",
      name_en: "Al Ezdihar Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003087,
      name_ar: "حي الاندلس",
      name_en: "Al Andalus Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003088,
      name_ar: "حي الروضة",
      name_en: "Al Rawdah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003089,
      name_ar: "حي الروابي",
      name_en: "Al Rawabi Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003090,
      name_ar: "حي الريان",
      name_en: "Al Rayan Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003091,
      name_ar: "حي ظهرة البديعة",
      name_en: "Dhahrat Al Badeah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003092,
      name_ar: "حي النظيم",
      name_en: "Al Nadheem Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003093,
      name_ar: "حي الرماية",
      name_en: "Al Rimayah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003094,
      name_ar: "حي البرية",
      name_en: "Al Bariyah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003095,
      name_ar: "حي طيبة",
      name_en: "Taybah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003096,
      name_ar: "حي المنصورية",
      name_en: "Mansuriyah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003097,
      name_ar: "حي ضاحية نمار",
      name_en: "Dahiyat Namar Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003098,
      name_ar: "حي المصفاة",
      name_en: "Al Misfat Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003099,
      name_ar: "حي السفارات",
      name_en: "Assafarat Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003100,
      name_ar: "خشم العان",
      name_en: "Khashm Al An",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003101,
      name_ar: "حي قرطبة",
      name_en: "Qurtubah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003102,
      name_ar: "حي طويق",
      name_en: "Tuwaiq Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003103,
      name_ar: "حي العوالي",
      name_en: "Al Awaly Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003104,
      name_ar: "حي الربيع",
      name_en: "Al Rabie Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003105,
      name_ar: "حي المغرزات",
      name_en: "Al Mughrazat Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003106,
      name_ar: "حي السلي",
      name_en: "Al Sulay Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003107,
      name_ar: "حي العقيق",
      name_en: "Al Aqeeq Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003108,
      name_ar: "حي النخيل",
      name_en: "Al Nakheel Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003109,
      name_ar: "حي الغدير",
      name_en: "Al Ghadeer Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003110,
      name_ar: "حي المروج",
      name_en: "Al Muruj Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003111,
      name_ar: "حي العود",
      name_en: "Al Oud Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003112,
      name_ar: "حي ثليم",
      name_en: "Thulaim Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003113,
      name_ar: "حي الشميسي",
      name_en: "Al Shumaisi Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003114,
      name_ar: "حي الوشام",
      name_en: "Al Wisham Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003115,
      name_ar: "منتزه سلام",
      name_en: "Salam Park",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003116,
      name_ar: "حي الدوبية",
      name_en: "Al Dubiyah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003117,
      name_ar: "حي معكال",
      name_en: "Meakal Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003118,
      name_ar: "حي جبرة",
      name_en: "Jabrah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003119,
      name_ar: "حي القرى",
      name_en: "Al Qura Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003120,
      name_ar: "حي المرقب",
      name_en: "Al Marqab Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003121,
      name_ar: "حي الفوطة",
      name_en: "Al Futah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003122,
      name_ar: "حي ام سليم",
      name_en: "Umm Saleem Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003123,
      name_ar: "حي الصحافة",
      name_en: "Al Sahafah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003125,
      name_ar: "حي الرائد",
      name_en: "Al Raed Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003126,
      name_ar: "حي العريجاء الغربي",
      name_en: "West Oraija Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003127,
      name_ar: "حي العريجاء",
      name_en: "Al Uraija Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003128,
      name_ar: "حي العريجاء الوسطى",
      name_en: "Middle Oraija Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003129,
      name_ar: "حي الحمراء",
      name_en: "Al Hamra Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003130,
      name_ar: "حي الدار البيضاء",
      name_en: "Al Dar Al Baida Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003131,
      name_ar: "حي البطيحا",
      name_en: "Al Butaiha Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003132,
      name_ar: "حي الزهراء",
      name_en: "Al Zahra Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003133,
      name_ar: "حي الفيحاء",
      name_en: "Al Fayha Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003134,
      name_ar: "حي المؤتمرات",
      name_en: "Al Mutamarat Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003135,
      name_ar: "حي الوسيطاء",
      name_en: "Al Wusayta Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003136,
      name_ar: "حي الجنادرية",
      name_en: "Al Janadriyah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003137,
      name_ar: "حي اشبيلية",
      name_en: "Ishbiliyah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003138,
      name_ar: "حي المعيزلة",
      name_en: "Al Maizalah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003139,
      name_ar: "حي اليرموك",
      name_en: "Al Yarmuk Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003140,
      name_ar: "حي المونسية",
      name_en: "Al Munisiyah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003141,
      name_ar: "حي الخزامى",
      name_en: "Al Khuzama Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003142,
      name_ar: "عرقة",
      name_en: "Irqah",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003143,
      name_ar: "حي ظهرة لبن",
      name_en: "Dhahrat Laban Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003144,
      name_ar: "حي حطين",
      name_en: "Hitteen Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003145,
      name_ar: "حي الملقا",
      name_en: "Al Malqa Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003146,
      name_ar: "حي القيروان",
      name_en: "Al Qairawan Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003147,
      name_ar: "حي الياسمين",
      name_en: "Al Yasmeen Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003148,
      name_ar: "حي العارض",
      name_en: "Al Arid Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003149,
      name_ar: "مطار الملك خالد",
      name_en: "King Khalid International Airport",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003150,
      name_ar: "حي النرجس",
      name_en: "Al Narjis Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003151,
      name_ar: "جامعة الامام محمد بن سعود الاسلامية",
      name_en: "Imam Muhammed Bin Saud Islamic University",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003152,
      name_ar: "حي بنبان",
      name_en: "Banban Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003153,
      name_ar: "حي الرمال",
      name_en: "Al Rimal Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003155,
      name_ar: "حي غرناطة",
      name_en: "Ghirnatah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003156,
      name_ar: "حي الدحو",
      name_en: "Al Dahou Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003157,
      name_ar: "حي العماجية",
      name_en: "Al Ammajiyah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003158,
      name_ar: "حي هيت",
      name_en: "Hyt Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003159,
      name_ar: "حي الحائر",
      name_en: "Al Haer Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003161,
      name_ar: "حي ام الشعال",
      name_en: "Umm Al Shaal Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003162,
      name_ar: "حي الغنامية",
      name_en: "Al Ghannamiyah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003163,
      name_ar: "حي عريض",
      name_en: "Oraid Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003164,
      name_ar: "حي بدر",
      name_en: "Badr Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003165,
      name_ar: "حي المهدية",
      name_en: "Al Mahdiyah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003166,
      name_ar: "جامعة الملك سعود",
      name_en: "King Saud University",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003167,
      name_ar: "حي النسيم الغربي",
      name_en: "West Naseem Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003168,
      name_ar: "حي المشاعل",
      name_en: "Al Mishael Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003169,
      name_ar: "حي الندوة",
      name_en: "Al Nadwah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003172,
      name_ar: "حي وادي لبن",
      name_en: "Wady Laban Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003174,
      name_ar: "حي السدرة",
      name_en: "Al Sidrah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003175,
      name_ar: "حي التضامن",
      name_en: "Al Tadamon Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003176,
      name_ar: "مدينة الملك عبدالله للطاقة",
      name_en: "King Abdullah City For Energy",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003178,
      name_ar: "حي الرحاب",
      name_en: "Al Rihab Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003179,
      name_ar: "حي المجد",
      name_en: "Al Majd Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003180,
      name_ar: "حي الدانة",
      name_en: "Al Danah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003182,
      name_ar: "حي الرسالة",
      name_en: "Al Risalah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003183,
      name_ar: "حي الخير",
      name_en: "Al Khair Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003184,
      name_ar: "حي الفرسان",
      name_en: "Al Fursan Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003185,
      name_ar: "حي الشعلة",
      name_en: "Al Sholah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003186,
      name_ar: "حي الراية",
      name_en: "Al Rayah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003187,
      name_ar: "حي الزهور",
      name_en: "Al Zahour Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003188,
      name_ar: "حي الزاهر",
      name_en: "Al Zaher Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003189,
      name_ar: "حي المرجان",
      name_en: "Al Marjan Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003190,
      name_ar: "حي البيان",
      name_en: "Al Bayan Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003191,
      name_ar: "حي العلا",
      name_en: "Al Ula Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003192,
      name_ar: "حي المشرق",
      name_en: "Al Mashriq Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003193,
      name_ar: "حي النخبة",
      name_en: "Al Nakhbah Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003194,
      name_ar: "حي السحاب",
      name_en: "Al Sahab Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
    {
      id: 10100003195,
      name_ar: "حي الوسام",
      name_en: "Al Wasam Dist.",
      city_id: 3,
      city_name_ar: "الرياض",
      city_name_en: "Riyadh",
      country_name_en: "Saudi Arabia",
      country_name_ar: "السعودية",
    },
  ],
};
