// src/app/[locale]/contact/data/countries.ts
export const countries = [
  // الدول العربية أولاً
  { code: "sa", dialCode: "+966", name: "المملكة العربية السعودية" },
  { code: "ae", dialCode: "+971", name: "دولة الإمارات العربية المتحدة" },
  { code: "kw", dialCode: "+965", name: "دولة الكويت" },
  { code: "qa", dialCode: "+974", name: "دولة قطر" },
  { code: "bh", dialCode: "+973", name: "مملكة البحرين" },
  { code: "om", dialCode: "+968", name: "سلطنة عُمان" },
  { code: "jo", dialCode: "+962", name: "المملكة الأردنية الهاشمية" },
  { code: "eg", dialCode: "+20", name: "جمهورية مصر العربية" },
  { code: "lb", dialCode: "+961", name: "الجمهورية اللبنانية" },
  { code: "sy", dialCode: "+963", name: "الجمهورية العربية السورية" },
  { code: "iq", dialCode: "+964", name: "جمهورية العراق" },
  { code: "ye", dialCode: "+967", name: "الجمهورية اليمنية" },
  { code: "ps", dialCode: "+970", name: "دولة فلسطين" },
  { code: "ma", dialCode: "+212", name: "المملكة المغربية" },
  {
    code: "dz",
    dialCode: "+213",
    name: "الجمهورية الجزائرية الديمقراطية الشعبية",
  },
  { code: "tn", dialCode: "+216", name: "الجمهورية التونسية" },
  { code: "ly", dialCode: "+218", name: "دولة ليبيا" },
  { code: "sd", dialCode: "+249", name: "جمهورية السودان" },
  { code: "so", dialCode: "+252", name: "جمهورية الصومال الفيدرالية" },
  { code: "dj", dialCode: "+253", name: "جمهورية جيبوتي" },
  { code: "km", dialCode: "+269", name: "اتحاد جزر القمر" },
  { code: "mr", dialCode: "+222", name: "الجمهورية الإسلامية الموريتانية" },

  // باقي دول العالم مرتبة أبجدياً
  { code: "af", dialCode: "+93", name: "أفغانستان" },
  { code: "al", dialCode: "+355", name: "ألبانيا" },
  { code: "ad", dialCode: "+376", name: "أندورا" },
  { code: "ao", dialCode: "+244", name: "أنغولا" },
  { code: "ag", dialCode: "+1268", name: "أنتيغوا وباربودا" },
  { code: "ar", dialCode: "+54", name: "الأرجنتين" },
  { code: "am", dialCode: "+374", name: "أرمينيا" },
  { code: "au", dialCode: "+61", name: "أستراليا" },
  { code: "at", dialCode: "+43", name: "النمسا" },
  { code: "az", dialCode: "+994", name: "أذربيجان" },
  { code: "bs", dialCode: "+1242", name: "الباهاما" },
  { code: "bd", dialCode: "+880", name: "بنغلاديش" },
  { code: "bb", dialCode: "+1246", name: "بربادوس" },
  { code: "by", dialCode: "+375", name: "بيلاروسيا" },
  { code: "be", dialCode: "+32", name: "بلجيكا" },
  { code: "bz", dialCode: "+501", name: "بليز" },
  { code: "bj", dialCode: "+229", name: "بنين" },
  { code: "bt", dialCode: "+975", name: "بوتان" },
  { code: "bo", dialCode: "+591", name: "بوليفيا" },
  { code: "ba", dialCode: "+387", name: "البوسنة والهرسك" },
  { code: "bw", dialCode: "+267", name: "بوتسوانا" },
  { code: "br", dialCode: "+55", name: "البرازيل" },
  { code: "bn", dialCode: "+673", name: "بروناي" },
  { code: "bg", dialCode: "+359", name: "بلغاريا" },
  { code: "bf", dialCode: "+226", name: "بوركينا فاسو" },
  { code: "bi", dialCode: "+257", name: "بوروندي" },
  { code: "cv", dialCode: "+238", name: "الرأس الأخضر" },
  { code: "kh", dialCode: "+855", name: "كمبوديا" },
  { code: "cm", dialCode: "+237", name: "الكاميرون" },
  { code: "ca", dialCode: "+1", name: "كندا" },
  { code: "cf", dialCode: "+236", name: "جمهورية أفريقيا الوسطى" },
  { code: "td", dialCode: "+235", name: "تشاد" },
  { code: "cl", dialCode: "+56", name: "تشيلي" },
  { code: "cn", dialCode: "+86", name: "الصين" },
  { code: "co", dialCode: "+57", name: "كولومبيا" },
  { code: "cg", dialCode: "+242", name: "الكونغو" },
  { code: "cd", dialCode: "+243", name: "جمهورية الكونغو الديمقراطية" },
  { code: "cr", dialCode: "+506", name: "كوستاريكا" },
  { code: "ci", dialCode: "+225", name: "ساحل العاج" },
  { code: "hr", dialCode: "+385", name: "كرواتيا" },
  { code: "cu", dialCode: "+53", name: "كوبا" },
  { code: "cy", dialCode: "+357", name: "قبرص" },
  { code: "cz", dialCode: "+420", name: "جمهورية التشيك" },
  { code: "dk", dialCode: "+45", name: "الدنمارك" },
  { code: "dm", dialCode: "+1767", name: "دومينيكا" },
  { code: "do", dialCode: "+1", name: "جمهورية الدومينيكان" },
  { code: "ec", dialCode: "+593", name: "الإكوادور" },
  { code: "sv", dialCode: "+503", name: "السلفادور" },
  { code: "gq", dialCode: "+240", name: "غينيا الاستوائية" },
  { code: "er", dialCode: "+291", name: "إريتريا" },
  { code: "ee", dialCode: "+372", name: "إستونيا" },
  { code: "sz", dialCode: "+268", name: "إسواتيني" },
  { code: "et", dialCode: "+251", name: "إثيوبيا" },
  { code: "fj", dialCode: "+679", name: "فيجي" },
  { code: "fi", dialCode: "+358", name: "فنلندا" },
  { code: "fr", dialCode: "+33", name: "فرنسا" },
  { code: "ga", dialCode: "+241", name: "الغابون" },
  { code: "gm", dialCode: "+220", name: "غامبيا" },
  { code: "ge", dialCode: "+995", name: "جورجيا" },
  { code: "de", dialCode: "+49", name: "ألمانيا" },
  { code: "gh", dialCode: "+233", name: "غانا" },
  { code: "gr", dialCode: "+30", name: "اليونان" },
  { code: "gd", dialCode: "+1473", name: "غرينادا" },
  { code: "gt", dialCode: "+502", name: "غواتيمالا" },
  { code: "gn", dialCode: "+224", name: "غينيا" },
  { code: "gw", dialCode: "+245", name: "غينيا بيساو" },
  { code: "gy", dialCode: "+592", name: "غيانا" },
  { code: "ht", dialCode: "+509", name: "هايتي" },
  { code: "hn", dialCode: "+504", name: "هندوراس" },
  { code: "hu", dialCode: "+36", name: "المجر" },
  { code: "is", dialCode: "+354", name: "آيسلندا" },
  { code: "in", dialCode: "+91", name: "الهند" },
  { code: "id", dialCode: "+62", name: "إندونيسيا" },
  { code: "ir", dialCode: "+98", name: "إيران" },
  { code: "ie", dialCode: "+353", name: "أيرلندا" },
  { code: "il", dialCode: "+972", name: "إسرائيل" },
  { code: "it", dialCode: "+39", name: "إيطاليا" },
  { code: "jm", dialCode: "+1876", name: "جامايكا" },
  { code: "jp", dialCode: "+81", name: "اليابان" },
  { code: "kz", dialCode: "+7", name: "كازاخستان" },
  { code: "ke", dialCode: "+254", name: "كينيا" },
  { code: "ki", dialCode: "+686", name: "كيريباتي" },
  { code: "kp", dialCode: "+850", name: "كوريا الشمالية" },
  { code: "kr", dialCode: "+82", name: "كوريا الجنوبية" },
  { code: "xk", dialCode: "+383", name: "كوسوفو" },
  { code: "kg", dialCode: "+996", name: "قيرغيزستان" },
  { code: "la", dialCode: "+856", name: "لاوس" },
  { code: "lv", dialCode: "+371", name: "لاتفيا" },
  { code: "ls", dialCode: "+266", name: "ليسوتو" },
  { code: "lr", dialCode: "+231", name: "ليبيريا" },
  { code: "li", dialCode: "+423", name: "ليختنشتاين" },
  { code: "lt", dialCode: "+370", name: "ليتوانيا" },
  { code: "lu", dialCode: "+352", name: "لوكسمبورغ" },
  { code: "mg", dialCode: "+261", name: "مدغشقر" },
  { code: "mw", dialCode: "+265", name: "ملاوي" },
  { code: "my", dialCode: "+60", name: "ماليزيا" },
  { code: "mv", dialCode: "+960", name: "جزر المالديف" },
  { code: "ml", dialCode: "+223", name: "مالي" },
  { code: "mt", dialCode: "+356", name: "مالطا" },
  { code: "mh", dialCode: "+692", name: "جزر مارشال" },
  { code: "mu", dialCode: "+230", name: "موريشيوس" },
  { code: "mx", dialCode: "+52", name: "المكسيك" },
  { code: "fm", dialCode: "+691", name: "ميكرونيزيا" },
  { code: "md", dialCode: "+373", name: "مولدوفا" },
  { code: "mc", dialCode: "+377", name: "موناكو" },
  { code: "mn", dialCode: "+976", name: "منغوليا" },
  { code: "me", dialCode: "+382", name: "الجبل الأسود" },
  { code: "mz", dialCode: "+258", name: "موزمبيق" },
  { code: "mm", dialCode: "+95", name: "ميانمار" },
  { code: "na", dialCode: "+264", name: "ناميبيا" },
  { code: "nr", dialCode: "+674", name: "ناورو" },
  { code: "np", dialCode: "+977", name: "نيبال" },
  { code: "nl", dialCode: "+31", name: "هولندا" },
  { code: "nz", dialCode: "+64", name: "نيوزيلندا" },
  { code: "ni", dialCode: "+505", name: "نيكاراغوا" },
  { code: "ne", dialCode: "+227", name: "النيجر" },
  { code: "ng", dialCode: "+234", name: "نيجيريا" },
  { code: "mk", dialCode: "+389", name: "مقدونيا الشمالية" },
  { code: "no", dialCode: "+47", name: "النرويج" },
  { code: "pk", dialCode: "+92", name: "باكستان" },
  { code: "pw", dialCode: "+680", name: "بالاو" },
  { code: "pa", dialCode: "+507", name: "بنما" },
  { code: "pg", dialCode: "+675", name: "بابوا غينيا الجديدة" },
  { code: "py", dialCode: "+595", name: "باراغواي" },
  { code: "pe", dialCode: "+51", name: "بيرو" },
  { code: "ph", dialCode: "+63", name: "الفلبين" },
  { code: "pl", dialCode: "+48", name: "بولندا" },
  { code: "pt", dialCode: "+351", name: "البرتغال" },
  { code: "ro", dialCode: "+40", name: "رومانيا" },
  { code: "ru", dialCode: "+7", name: "روسيا" },
  { code: "rw", dialCode: "+250", name: "رواندا" },
  { code: "kn", dialCode: "+1869", name: "سانت كيتس ونيفيس" },
  { code: "lc", dialCode: "+1758", name: "سانت لوسيا" },
  { code: "vc", dialCode: "+1784", name: "سانت فنسنت والغرينادين" },
  { code: "ws", dialCode: "+685", name: "ساموا" },
  { code: "sm", dialCode: "+378", name: "سان مارينو" },
  { code: "st", dialCode: "+239", name: "ساو تومي وبرينسيبي" },
  { code: "sn", dialCode: "+221", name: "السنغال" },
  { code: "rs", dialCode: "+381", name: "صربيا" },
  { code: "sc", dialCode: "+248", name: "سيشل" },
  { code: "sl", dialCode: "+232", name: "سيراليون" },
  { code: "sg", dialCode: "+65", name: "سنغافورة" },
  { code: "sk", dialCode: "+421", name: "سلوفاكيا" },
  { code: "si", dialCode: "+386", name: "سلوفينيا" },
  { code: "sb", dialCode: "+677", name: "جزر سليمان" },
  { code: "za", dialCode: "+27", name: "جنوب أفريقيا" },
  { code: "ss", dialCode: "+211", name: "جنوب السودان" },
  { code: "es", dialCode: "+34", name: "إسبانيا" },
  { code: "lk", dialCode: "+94", name: "سريلانكا" },
  { code: "sr", dialCode: "+597", name: "سورينام" },
  { code: "se", dialCode: "+46", name: "السويد" },
  { code: "ch", dialCode: "+41", name: "سويسرا" },
  { code: "tj", dialCode: "+992", name: "طاجيكستان" },
  { code: "tz", dialCode: "+255", name: "تنزانيا" },
  { code: "th", dialCode: "+66", name: "تايلاند" },
  { code: "tl", dialCode: "+670", name: "تيمور الشرقية" },
  { code: "tg", dialCode: "+228", name: "توغو" },
  { code: "to", dialCode: "+676", name: "تونغا" },
  { code: "tt", dialCode: "+1868", name: "ترينيداد وتوباغو" },
  { code: "tr", dialCode: "+90", name: "تركيا" },
  { code: "tm", dialCode: "+993", name: "تركمانستان" },
  { code: "tv", dialCode: "+688", name: "توفالو" },
  { code: "ug", dialCode: "+256", name: "أوغندا" },
  { code: "ua", dialCode: "+380", name: "أوكرانيا" },
  { code: "gb", dialCode: "+44", name: "المملكة المتحدة" },
  { code: "us", dialCode: "+1", name: "الولايات المتحدة الأمريكية" },
  { code: "uy", dialCode: "+598", name: "الأوروغواي" },
  { code: "uz", dialCode: "+998", name: "أوزبكستان" },
  { code: "vu", dialCode: "+678", name: "فانواتو" },
  { code: "va", dialCode: "+39", name: "الفاتيكان" },
  { code: "ve", dialCode: "+58", name: "فنزويلا" },
  { code: "vn", dialCode: "+84", name: "فيتنام" },
  { code: "zm", dialCode: "+260", name: "زامبيا" },
  { code: "zw", dialCode: "+263", name: "زيمبابوي" },
];
